#!/usr/bin/env python3
"""Generate the Cloudflare Worker web bundle from the canonical Pages sources."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "cloudflare" / "web-assets.js"
SOURCES = {
    "/index.html": (ROOT / "pages" / "index.html", "text/html; charset=utf-8"),
    "/en/index.html": (ROOT / "pages" / "en" / "index.html", "text/html; charset=utf-8"),
    "/404.html": (ROOT / "pages" / "404.html", "text/html; charset=utf-8"),
    "/assets/site.css": (ROOT / "pages" / "assets" / "site.css", "text/css; charset=utf-8"),
    "/assets/site.js": (ROOT / "pages" / "assets" / "site.js", "text/javascript; charset=utf-8"),
    "/assets/favicon.svg": (ROOT / "pages" / "assets" / "favicon.svg", "image/svg+xml; charset=utf-8"),
}

MIRROR_PATHS = (
    "index.html",
    "en/index.html",
    "404.html",
    "assets/site.css",
    "assets/site.js",
    "assets/favicon.svg",
)


def render() -> str:
    records = {}
    for route, (path, content_type) in SOURCES.items():
        body = path.read_text(encoding="utf-8")
        digest = hashlib.sha256(body.encode()).hexdigest()[:16]
        records[route] = {"body": body, "type": content_type, "etag": '"%s"' % digest}
    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    return (
        "// Generated by scripts/sync-web-assets.py; do not edit by hand.\n"
        f"export const WEB_ASSETS = Object.freeze({payload});\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    parser.add_argument("--mirror-root", type=Path, help="sync pages into <root>/AgentBoot")
    args = parser.parse_args()
    expected = render()
    ok = True
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("cloudflare/web-assets.js is stale; run scripts/sync-web-assets.py", file=sys.stderr)
            ok = False
    else:
        OUTPUT.write_text(expected, encoding="utf-8")

    if args.mirror_root:
        mirror = args.mirror_root.resolve() / "AgentBoot"
        for relative in MIRROR_PATHS:
            source = ROOT / "pages" / relative
            target = mirror / relative
            if target.is_file() and target.read_bytes() == source.read_bytes():
                continue
            if args.check:
                print(f"mirror is stale: {target}", file=sys.stderr)
                ok = False
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, target)
                print(f"updated {target}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
